version: '3'

networks:
  default:
    driver: bridge
services:
  php_fpm:
    volumes:
      - "./docker/php/php.ini-development:/usr/local/etc/php/php.ini"
  db_mysql:
    ports:
      - '${MYSQL_EXTERNAL_PORT}:3306'